project:
  type: website
  output-dir: docs
    
website:
  title: "EC910"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Lecture Handouts
        menu:
          - href: handout-1.qmd
            text: Handout 1
          - href: handout-2.qmd
            text: Handout 2
          - href: handout-3.qmd
            text: Handout 3
          - href: handout-4.qmd
            text: Handout 4
          - href: handout-5.qmd
            text: Handout 5
          - href: handout-6.qmd
            text: Handout 6 
          - href: handout-7.qmd
            text: Handout 7
          - href: handout-8.qmd
            text: Handout 8
      - text: Problem Sets
        menu:
          - href: problem-sets/ps-1/problem-set-1.html
            text: Problem Set 1
          - href: problem-sets/ps-1/problem-set-1-solutions.html
            text: Problem Set 1 (Solutions)
          - href: problem-set-2.qmd
            text: Problem Set 2
          - href: problem-set-2-solutions.qmd
            text: Problem Set 2 (Solutions) 
          - href: problem-set-3.qmd
            text: Problem Set 3
          - href: problem-set-3-solutions.qmd
            text: Problem Set 3 (Solutions) 
          - href: problem-set-4.qmd
            text: Problem Set 4
          - href: problem-set-4-solutions.qmd
            text: Problem Set 4 (Solutions)
          - href: problem-set-5.qmd
            text: Problem Set 5
          - href: problem-set-5-solutions.qmd
            text: Problem Set 5 (Solutions)
          - href: problem-set-6.qmd
            text: Problem Set 6
          - href: problem-set-6-solutions.qmd
            text: Problem Set 6 (Solutions)
      - text: Additional Material
        menu:
          - href: material-cef.qmd
            text: Conditional Expectation Function  
          - href: material-interpretation.qmd
            text: Interpreting Linear Models
          - href: material-dummy.qmd
            text: Dummy Variables
          - href: material-linearalgebra.qmd
            text: Linear Algebra
          - href: material-inference.qmd
            text: Statistical Inference
          

bibliography: references.bib

format:
  html:
    theme: 
      light: lightly
      dark: darkly
    toc: true              # Include a table of contents in the HTML output
    css: styles.css        # Optionally include custom CSS for styling

editor: source

execute:
  freeze: auto            # true is the option to not re-render anything new. 


