project:
  type: website
  output-dir: docs
  
website:
  title: "EC910"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Lecture Handouts
        menu:
          - href: handout-1.qmd
            text: Handout 1
          - href: handout-2.qmd
            text: Handout 2
          - href: handout-3.qmd
            text: Handout 3
          - href: handout-4.qmd
            text: Handout 4
      - text: Problem Sets
        menu:
          - href: problem-sets/ps-1/problem-set-1.html
            text: Problem Set 1
          - href: problem-sets/ps-1/problem-set-1-solutions.html
            text: Problem Set 1 (Solutions)
          - href: problem-set-2.qmd
            text: Problem Set 2
          - href: problem-set-2-solutions.qmd
            text: Problem Set 2 (Solutions) 
          - href: problem-set-3.qmd
            text: Problem Set 3            
      - text: Additional Material
        menu:
          - href: material-cef.qmd
            text: Conditional Expectation Function  
          - href: material-interpretation.qmd
            text: Interpreting Linear Models
          - href: material-dummy.qmd
            text: Dummy Variables
          - href: material-linearalgebra.qmd
            text: Linear Algebra
          

bibliography: references.bib

format:
  html:
    theme: 
      light: lightly
      dark: darkly
    toc: true              # Include a table of contents in the HTML output
    css: styles.css        # Optionally include custom CSS for styling

editor: source

execute:
  freeze: auto
