project:
  type: website
  output-dir: docs
  
website:
  title: "EC910"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Lectures
        menu:
          - href: lecture-1.qmd
            text: Lecture 1
          - href: lecture-2.qmd
            text: Lecture 2
          - href: lecture-3.qmd
            text: Lecture 3
      - text: Problem Sets
        menu:
          - href: problem-sets/problem-set-1.html
            text: Problem Set 1
      - text: Additional
        menu:
          - href: material-cef.qmd
            text: Conditional Expectation Function 
          - href: material-linearalgebra.qmd
            text: Linear Algebra

bibliography: references.bib

format:
  html:
    theme: 
      light: lightly
      dark: darkly
    toc: true              # Include a table of contents in the HTML output
    css: styles.css        # Optionally include custom CSS for styling

editor: source

execute:
  freeze: auto
