---
title: "Quantitative Methods: Econometrics B"
---

## Welcome to 'Metrics B!

This is not the official module website. The [EC910 (or EC987, 2024/25)](https://moodle.warwick.ac.uk/course/view.php?id=64258) Moodle-page is the primary source of communication and resources for this module. All material available on this website can be found there.

I designed this website as a means of testing out the Quarto package, developed by RStudio.[^1] This was partly as a way to develop my own skills and better incorporate the R language into the module. However, there are also accessibility benefits to this approach. Mathematical notation published in pdf's using LaTeX cannot be read by a screen reader, while LaTeX published in html can. In addition, the website has built-in dark-mode option (see top-right toggle). For those who prefer pdf (for printing and notetaking), each page contains a unique downloadable link.

[^1]: To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

**Please let me know if you find any mistakes in my notes or code.** In addition, I welcome suggestions on how to improve the R (or Stata) code provided in this module. I will endeavor to do my best to acknowledge the many people who have contributed to this material and my wider knowledge of this subject.

## Acknowledgements

I am building off material developed by Prof. Wiji Arulampalam, who taught this module from 2011-2024. Since arriving at Warwick in 2021, I have learned so much from Prof. Arulampalam's expertise and years of research and professional experience. More importantly, I have so enjoyed working alongside her as both colleague and friend. I wish her well in her retirement.  

I have also borrowed from material developed by Prof. Vadim Marmer (Vancouver School of Economics, UBC) who taught the Econometrics module I attended during my own Master's degree. I was the teaching assistant for this module from 2017-2019 and developed some additional notes found here. I am hugely indebted to Prof. Marmer, whose teaching and professional guidance have been foundational to my academic career. 

**I hope you enjoy this module!**

[Neil Lloyd](https://warwick.ac.uk/fac/soc/economics/staff/nlloyd/)

