<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>EC910</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>



<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">EC910</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-lecture-handouts" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Lecture Handouts</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-lecture-handouts">    
        <li>
    <a class="dropdown-item" href="./handout-1.html">
 <span class="dropdown-text">Handout 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./handout-2.html">
 <span class="dropdown-text">Handout 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./handout-3.html">
 <span class="dropdown-text">Handout 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./handout-4.html">
 <span class="dropdown-text">Handout 4</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-problem-sets" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Problem Sets</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-problem-sets">    
        <li>
    <a class="dropdown-item" href="./problem-sets/ps-1/problem-set-1.html">
 <span class="dropdown-text">Problem Set 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./problem-sets/ps-1/problem-set-1-solutions.html">
 <span class="dropdown-text">Problem Set 1 (Solutions)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./problem-set-2.html">
 <span class="dropdown-text">Problem Set 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./problem-set-2-solutions.html">
 <span class="dropdown-text">Problem Set 2 (Solutions)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./problem-set-3.html">
 <span class="dropdown-text">Problem Set 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./problem-set-3-solutions.html">
 <span class="dropdown-text">Problem Set 3 (Solutions)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./problem-set-4.html">
 <span class="dropdown-text">Problem Set 4</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-additional-material" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Additional Material</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-additional-material">    
        <li>
    <a class="dropdown-item" href="./material-cef.html">
 <span class="dropdown-text">Conditional Expectation Function</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./material-interpretation.html">
 <span class="dropdown-text">Interpreting Linear Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./material-dummy.html">
 <span class="dropdown-text">Dummy Variables</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./material-linearalgebra.html">
 <span class="dropdown-text">Linear Algebra</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#conditional-expectation-function" id="toc-conditional-expectation-function" class="nav-link active" data-scroll-target="#conditional-expectation-function">Conditional Expectation Function</a></li>
  <li><a href="#preamble" id="toc-preamble" class="nav-link" data-scroll-target="#preamble">Preamble</a></li>
  <li><a href="#questions" id="toc-questions" class="nav-link" data-scroll-target="#questions">Questions</a></li>
  <li><a href="#postamble" id="toc-postamble" class="nav-link" data-scroll-target="#postamble">Postamble</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="problem-set-2-solutions.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Problem Set 2 (SOLUTIONS)</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This problem set will take you through some Stata commands to estimate simple regression equations with dummy variables. You will learn how to interpret the estimated coefficients and test some linear hypotheses. Interpretation of these coefficients will be useful when we do treatment evaluation models later in term 1.</p>
<p>The hypothesis tests discussed in this problem set include standard T-tests and F-tests, which is assumed undergraduate knowledge for this module.</p>
<p>You will need to download the dataset problemset2.dta, which is available on Moodle.</p>
<section id="conditional-expectation-function" class="level2">
<h2 class="anchored" data-anchor-id="conditional-expectation-function">Conditional Expectation Function</h2>
<p>Consider the Conditional Expectation Function (CEF), <span class="math inline">\(E[Y_i|X_i]\)</span>. If <span class="math inline">\(X\)</span> takes on discrete values: <span class="math inline">\(X_i\in\{x_1,x_2,...,x_m\}\)</span>, then</p>
<p><span class="math display">\[
    E[Y_i|X_i] =  E[Y_i|X_i=x_1]\cdot\mathbf{1}\{X_i = x_1\}+...+E[Y_i|X_i=x_m]\cdot\mathbf{1}\{X_i = x_m\}
\]</span> where <span class="math inline">\(\mathbf{1}\{X_i = x_m\}\)</span> is a dummy variable, <span class="math inline">\(=1\)</span> when <span class="math inline">\(X_i=x_m\)</span>. Since the values of <span class="math inline">\(X_i\)</span> are mutually exclusive there is no overlap of these dummy variables.</p>
<p>Note, we do not need to assume that <span class="math inline">\(X\)</span> is a single random variable. It can be a vector of random variables that takes on discrete values.</p>
<p>We can re-arrange this expression using anyone of the values of <span class="math inline">\(X\)</span>. The natural option is to choose the first, but this is arbitrary.</p>
<p><span class="math display">\[
\begin{aligned}
    E[Y_i|X_i] =&amp; E[Y_i|X_i=x_1]+ (E[Y_i|X_i=x_2]-E[Y_i|X_i=x_1])\cdot\mathbf{1}\{X_i = x_2\}+... \\
&amp;+(E[Y_i|X_i=x_m]-E[Y_i|X_i=x_1])\cdot\mathbf{1}\{X_i = x_m\}
\end{aligned}
\]</span></p>
<p>Since, <span class="math inline">\(E[Y_i|X_i = x_m]\)</span> is a constant (<span class="math inline">\(X_i\)</span> is set to a specific value), we can express the CEF as a function that is linear in parameters.</p>
<p><span class="math display">\[
    E[Y_i|X_i] = \beta_1 + \beta_2D_{i2} + ... + \beta_m D_{im}
\]</span></p>
<p>where <span class="math inline">\(D_{im}=\mathbf{1}\{X_i = x_m\}\)</span>.</p>
</section>
<section id="preamble" class="level2">
<h2 class="anchored" data-anchor-id="preamble">Preamble</h2>
<div id="e11dbd64" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display">
<style>div.jp-Notebook .datagrid-container {min-height: 448px; }</style>
</div>
</div>
<p>Create a do-file for this problem set and include a preamble that sets the directory and opens the data. For example,</p>
<div id="1e92a31c" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">clear</span> </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">//or, to remove all stored values (including macros, matrices, scalars, etc.) </span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>*<span class="kw">clear</span> <span class="ot">all</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>* Replace <span class="ot">$rootdir</span> with the relevant path to <span class="kw">on</span> your <span class="kw">local</span> harddrive.</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>cd <span class="st">"$rootdir/problem-sets/ps-2"</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>cap <span class="fu">log</span> <span class="kw">close</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">log</span> <span class="kw">using</span> problem-<span class="kw">set</span>-2-<span class="fu">log</span>.txt, <span class="kw">replace</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="kw">use</span> problem-<span class="kw">set</span>-2-<span class="kw">data</span>.dta</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="questions" class="level2">
<h2 class="anchored" data-anchor-id="questions">Questions</h2>
<p><strong>1.</strong> Consider the <span class="math inline">\(E[ln(Wage_i)|Gender_i]\)</span>, where <span class="math inline">\(Gender_i\in\{1 ``Male'', 2 ``Female''\}\)</span>. Show that this CEF implies a linear model,</p>
<p><span class="math display">\[
    ln(Wage_i) = \beta_1 + \beta_2 D_{i2} + \varepsilon_i
\]</span></p>
<p>What do the parameters <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span> imply?</p>
<p><span class="math display">\[
E[ln(Wage_i)|G_i] = E[ln(Wage_i)|G_i=1]+ (E[ln(Wage_i)|G_i=2]-E[ln(Wage_i)|G_i=1])\cdot\mathbf{1}\{G_i = 2\}
\]</span> <span class="math display">\[
= \beta_1+ \beta_2D_{i2}
\]</span> <span class="math inline">\(\Rightarrow E[\varepsilon_i|D_{i2}]=0\)</span>.</p>
<p><strong>2.</strong> Regress <code>lwage</code> (log wage) on just a set of binary indicators that will enable you to test the hypothesis that males and females are on average, paid the same wage, ceteris paribus. Test this hypothesis.</p>
<div id="0b845848" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> lwage female</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>* <span class="kw">or</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> male=1-female</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> lwage male</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      Source |       SS           df       MS      Number of obs   =     4,165
-------------+----------------------------------   F(1, 4163)      =    491.72
       Model |  93.6914807         1  93.6914807   Prob &gt; F        =    0.0000
    Residual |  793.213421     4,163  .190538895   R-squared       =    0.1056
-------------+----------------------------------   Adj R-squared   =    0.1054
       Total |  886.904902     4,164  .212993492   Root MSE        =    .43651

------------------------------------------------------------------------------
       lwage | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
      female |  -.4744661   .0213967   -22.17   0.000     -.516415   -.4325171
       _cons |   6.729774     .00718   937.29   0.000     6.715697     6.74385
------------------------------------------------------------------------------

      Source |       SS           df       MS      Number of obs   =     4,165
-------------+----------------------------------   F(1, 4163)      =    491.72
       Model |  93.6914807         1  93.6914807   Prob &gt; F        =    0.0000
    Residual |  793.213421     4,163  .190538895   R-squared       =    0.1056
-------------+----------------------------------   Adj R-squared   =    0.1054
       Total |  886.904902     4,164  .212993492   Root MSE        =    .43651

------------------------------------------------------------------------------
       lwage | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
        male |   .4744661   .0213967    22.17   0.000     .4325171     .516415
       _cons |   6.255308    .020156   310.34   0.000     6.215791    6.294824
------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>Alternatively, you could use Stata’s factor notation:</p>
<div id="89e71d6d" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> lwage i.female</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co">//note: defaults to smallest value as base category. This can be changed as follows.</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> lwage ib1.female</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      Source |       SS           df       MS      Number of obs   =     4,165
-------------+----------------------------------   F(1, 4163)      =    491.72
       Model |  93.6914807         1  93.6914807   Prob &gt; F        =    0.0000
    Residual |  793.213421     4,163  .190538895   R-squared       =    0.1056
-------------+----------------------------------   Adj R-squared   =    0.1054
       Total |  886.904902     4,164  .212993492   Root MSE        =    .43651

------------------------------------------------------------------------------
       lwage | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
    1.female |  -.4744661   .0213967   -22.17   0.000     -.516415   -.4325171
       _cons |   6.729774     .00718   937.29   0.000     6.715697     6.74385
------------------------------------------------------------------------------

      Source |       SS           df       MS      Number of obs   =     4,165
-------------+----------------------------------   F(1, 4163)      =    491.72
       Model |  93.6914807         1  93.6914807   Prob &gt; F        =    0.0000
    Residual |  793.213421     4,163  .190538895   R-squared       =    0.1056
-------------+----------------------------------   Adj R-squared   =    0.1054
       Total |  886.904902     4,164  .212993492   Root MSE        =    .43651

------------------------------------------------------------------------------
       lwage | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
    0.female |   .4744661   .0213967    22.17   0.000     .4325171     .516415
       _cons |   6.255308    .020156   310.34   0.000     6.215791    6.294824
------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>It is evident from the test p-value that the difference is statistically significantly. Note, the standard <code>reg</code> command assume homoskedastic SEs. If we believe that the variance varies of (log of) wages varies with gender, we should estimate heteroskedastic SEs. However, in this instance it will not make a difference to the conclusion.</p>
<div id="0a368339" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> lwage female, <span class="fu">r</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Linear regression                               Number of obs     =      4,165
                                                F(1, 4163)        =     520.64
                                                Prob &gt; F          =     0.0000
                                                R-squared         =     0.1056
                                                Root MSE          =     .43651

------------------------------------------------------------------------------
             |               Robust
       lwage | Coefficient  std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
      female |  -.4744661   .0207939   -22.82   0.000    -.5152332   -.4336989
       _cons |   6.729774   .0072089   933.53   0.000      6.71564    6.743907
------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p><strong>3.</strong> Extend the specification in (2) that will enable you to test the hypothesis that there is no difference in the wages between the following gender-ethnicity groups. Begin by defining the following dummy variables:</p>
<ul>
<li><p><code>female_black</code> = <code>female</code><span class="math inline">\(\times\)</span><code>black</code></p></li>
<li><p><code>male_black</code> = (1-<code>female</code>)<span class="math inline">\(\times\)</span><code>black</code></p></li>
<li><p><code>female_nonblack</code> = <code>female</code><span class="math inline">\(\times\)</span>(1-<code>black</code>)</p></li>
<li><p><code>male_nonblack</code> = (1-<code>female</code>)<span class="math inline">\(\times\)</span>(1-<code>black</code>)</p></li>
</ul>
<div id="ef275188" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> female_black=female*<span class="bn">black</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> female_nonblack=female*(1-<span class="bn">black</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> male_black=(1-female)*<span class="bn">black</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> male_nonblack=(1-female)*(1-<span class="bn">black</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then estimate the following regressions:</p>
<ol type="a">
<li><p><code>lwage</code> on <code>female_black</code>, <code>female_nonblack</code>, <code>male_black</code>, <code>male_nonblack</code> (without a constant: option <code>nocons</code>)</p></li>
<li><p><code>lwage</code> on <code>female</code>, <code>black</code>, <code>female_black</code></p></li>
<li><p><code>lwage</code> on <code>female_black</code>, <code>female_nonblack</code>, <code>male_black</code></p></li>
</ol>
<p>For some of these exercises you may be able to use Stata’s factor notation. However, in some instances you will need to manually create the above dummy-variable interactions.</p>
<p>In each case, identify the base category and write down the parameters of the (implied) model in terms of conditional expectations.</p>
<div id="6927af08" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>* (a)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> lwage female_black female_nonblack male_black male_nonblack</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co">// note, Stata has dropped one variable due to perfect collinearity</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> lwage female_black female_nonblack male_black male_nonblack, <span class="kw">nocons</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>note: male_black omitted because of collinearity.

      Source |       SS           df       MS      Number of obs   =     4,165
-------------+----------------------------------   F(3, 4161)      =    191.17
       Model |  107.436063         3  35.8120209   Prob &gt; F        =    0.0000
    Residual |  779.468839     4,161  .187327287   R-squared       =    0.1211
-------------+----------------------------------   Adj R-squared   =    0.1205
       Total |  886.904902     4,164  .212993492   Root MSE        =    .43281

------------------------------------------------------------------------------
       lwage | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
female_black |  -.4434409   .0523433    -8.47   0.000    -.5460617     -.34082
female_non~k |  -.2101553   .0383456    -5.48   0.000    -.2853332   -.1349774
  male_black |          0  (omitted)
male_nonbl~k |   .2239593   .0317691     7.05   0.000     .1616749    .2862436
       _cons |   6.517691   .0309152   210.82   0.000     6.457081    6.578301
------------------------------------------------------------------------------

      Source |       SS           df       MS      Number of obs   =     4,165
-------------+----------------------------------   F(4, 4161)      &gt;  99999.00
       Model |  185756.485         4  46439.1213   Prob &gt; F        =    0.0000
    Residual |  779.468839     4,161  .187327287   R-squared       =    0.9958
-------------+----------------------------------   Adj R-squared   =    0.9958
       Total |  186535.954     4,165  44.7865436   Root MSE        =    .43281

------------------------------------------------------------------------------
       lwage | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
female_black |    6.07425   .0422382   143.81   0.000     5.991441     6.15706
female_non~k |   6.307536   .0226856   278.04   0.000      6.26306    6.352012
  male_black |   6.517691   .0309152   210.82   0.000     6.457081    6.578301
male_nonbl~k |    6.74165   .0073159   921.51   0.000     6.727307    6.755993
------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>This model returns four parameter-estimates, each corresponding to the four gender-ethnicity groups. These are essentially conditional mean estimates.</p>
<div id="e041d018" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>* (b)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> lwage female <span class="bn">black</span> female_black</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co">// or, using factor notation:</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> lwage i.female##i.<span class="bn">black</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      Source |       SS           df       MS      Number of obs   =     4,165
-------------+----------------------------------   F(3, 4161)      =    191.17
       Model |  107.436063         3  35.8120209   Prob &gt; F        =    0.0000
    Residual |  779.468839     4,161  .187327287   R-squared       =    0.1211
-------------+----------------------------------   Adj R-squared   =    0.1205
       Total |  886.904902     4,164  .212993492   Root MSE        =    .43281

------------------------------------------------------------------------------
       lwage | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
      female |  -.4341146   .0238361   -18.21   0.000     -.480846   -.3873832
       black |  -.2239593   .0317691    -7.05   0.000    -.2862436   -.1616749
female_black |  -.0093263    .057515    -0.16   0.871    -.1220865    .1034339
       _cons |    6.74165   .0073159   921.51   0.000     6.727307    6.755993
------------------------------------------------------------------------------

      Source |       SS           df       MS      Number of obs   =     4,165
-------------+----------------------------------   F(3, 4161)      =    191.17
       Model |  107.436063         3  35.8120209   Prob &gt; F        =    0.0000
    Residual |  779.468839     4,161  .187327287   R-squared       =    0.1211
-------------+----------------------------------   Adj R-squared   =    0.1205
       Total |  886.904902     4,164  .212993492   Root MSE        =    .43281

------------------------------------------------------------------------------
       lwage | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
    1.female |  -.4341146   .0238361   -18.21   0.000     -.480846   -.3873832
     1.black |  -.2239593   .0317691    -7.05   0.000    -.2862436   -.1616749
             |
female#black |
        1 1  |  -.0093263    .057515    -0.16   0.871    -.1220865    .1034339
             |
       _cons |    6.74165   .0073159   921.51   0.000     6.727307    6.755993
------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>In this model, we have the following:</p>
<ul>
<li><p><span class="math inline">\(\beta_1 = E[ln(Wage_i)|F = 0,B = 0]\)</span></p></li>
<li><p><span class="math inline">\(\beta_2 = E[ln(Wage_i)|F = 1,B = 0]-E[ln(Wage_i)|F = 0,B = 0]\)</span></p></li>
<li><p><span class="math inline">\(\beta_3 = E[ln(Wage_i)|F = 0,B = 1]-E[ln(Wage_i)|F = 0,B = 0]\)</span></p></li>
<li><p><span class="math inline">\(\beta_4 = (E[ln(Wage_i)|F = 1,B = 1]-E[ln(Wage_i)|F = 0,B = 1])-(E[ln(Wage_i)|F = 1,B = 0]-E[ln(Wage_i)|F = 0,B = 0])\)</span></p></li>
</ul>
<div id="fe77361f" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>* (c) </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> lwage female_black female_nonblack male_black  </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co">// note, this one is harder to replicate using factor notation. </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      Source |       SS           df       MS      Number of obs   =     4,165
-------------+----------------------------------   F(3, 4161)      =    191.17
       Model |  107.436063         3  35.8120209   Prob &gt; F        =    0.0000
    Residual |  779.468839     4,161  .187327287   R-squared       =    0.1211
-------------+----------------------------------   Adj R-squared   =    0.1205
       Total |  886.904902     4,164  .212993492   Root MSE        =    .43281

------------------------------------------------------------------------------
       lwage | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
female_black |  -.6674001   .0428671   -15.57   0.000    -.7514426   -.5833576
female_non~k |  -.4341146   .0238361   -18.21   0.000     -.480846   -.3873832
  male_black |  -.2239593   .0317691    -7.05   0.000    -.2862436   -.1616749
       _cons |    6.74165   .0073159   921.51   0.000     6.727307    6.755993
------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>In this model, we have the following:</p>
<ul>
<li><p><span class="math inline">\(\beta_1 = E[ln(Wage_i)|F = 0,B = 0]\)</span></p></li>
<li><p><span class="math inline">\(\beta_2 = E[ln(Wage_i)|F = 1,B = 1]-E[ln(Wage_i)|F = 0,B = 0]\)</span></p></li>
<li><p><span class="math inline">\(\beta_3 = E[ln(Wage_i)|F = 1,B = 0]-E[ln(Wage_i)|F = 0,B = 0]\)</span></p></li>
<li><p><span class="math inline">\(\beta_4 = E[ln(Wage_i)|F = 0,B = 1]-E[ln(Wage_i)|F = 0,B = 0]\)</span></p></li>
</ul>
<p><strong>4.</strong> Compare the estimated coefficients with the sample average values for the lwage for the four subgroups. What do you see?</p>
<div id="9d684d76" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="kw">table</span> female <span class="bn">black</span>, stat(<span class="kw">mean</span> lwage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
------------------------------------------------
               |               black            
               |         0          1      Total
---------------+--------------------------------
female or male |                                
  0            |   6.74165   6.517691   6.729774
  1            |  6.307536    6.07425   6.255308
  Total        |  6.700755   6.363002   6.676346
------------------------------------------------</code></pre>
</div>
</div>
<p>You can compute the coefficients from each model simply using these averages.</p>
<p><strong>5.</strong> In each of the above models, describe the null hypothesis you would test to evaluate whether there is a significant earnings difference between the earnings of black and non-black females.</p>
<ol type="a">
<li><p><span class="math inline">\(H_0: \beta_1 = \beta_2\)</span></p></li>
<li><p><span class="math inline">\(H_0: \beta_3 + \beta_4 = 0\)</span></p></li>
<li><p><span class="math inline">\(H_0: \beta_2 - \beta_3 = 0\)</span></p></li>
</ol>
<p><strong>6.</strong> Verify your solution to 4 by performing a test using the three set of regression output. You can use the post-estimation <code>test</code> command.</p>
<div id="673c4b58" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> lwage female_black female_nonblack male_black male_nonblack, <span class="kw">nocons</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="kw">test</span> female_black = female_nonblack</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> lwage female <span class="bn">black</span> female_black</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="kw">test</span> female_black + <span class="bn">black</span> = 0</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> lwage female_black female_nonblack male_black  </span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="kw">test</span> female_black - female_nonblack = 0</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      Source |       SS           df       MS      Number of obs   =     4,165
-------------+----------------------------------   F(4, 4161)      &gt;  99999.00
       Model |  185756.485         4  46439.1213   Prob &gt; F        =    0.0000
    Residual |  779.468839     4,161  .187327287   R-squared       =    0.9958
-------------+----------------------------------   Adj R-squared   =    0.9958
       Total |  186535.954     4,165  44.7865436   Root MSE        =    .43281

------------------------------------------------------------------------------
       lwage | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
female_black |    6.07425   .0422382   143.81   0.000     5.991441     6.15706
female_non~k |   6.307536   .0226856   278.04   0.000      6.26306    6.352012
  male_black |   6.517691   .0309152   210.82   0.000     6.457081    6.578301
male_nonbl~k |    6.74165   .0073159   921.51   0.000     6.727307    6.755993
------------------------------------------------------------------------------

 ( 1)  female_black - female_nonblack = 0

       F(  1,  4161) =   23.68
            Prob &gt; F =    0.0000

      Source |       SS           df       MS      Number of obs   =     4,165
-------------+----------------------------------   F(3, 4161)      =    191.17
       Model |  107.436063         3  35.8120209   Prob &gt; F        =    0.0000
    Residual |  779.468839     4,161  .187327287   R-squared       =    0.1211
-------------+----------------------------------   Adj R-squared   =    0.1205
       Total |  886.904902     4,164  .212993492   Root MSE        =    .43281

------------------------------------------------------------------------------
       lwage | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
      female |  -.4341146   .0238361   -18.21   0.000     -.480846   -.3873832
       black |  -.2239593   .0317691    -7.05   0.000    -.2862436   -.1616749
female_black |  -.0093263    .057515    -0.16   0.871    -.1220865    .1034339
       _cons |    6.74165   .0073159   921.51   0.000     6.727307    6.755993
------------------------------------------------------------------------------

 ( 1)  black + female_black = 0

       F(  1,  4161) =   23.68
            Prob &gt; F =    0.0000

      Source |       SS           df       MS      Number of obs   =     4,165
-------------+----------------------------------   F(3, 4161)      =    191.17
       Model |  107.436063         3  35.8120209   Prob &gt; F        =    0.0000
    Residual |  779.468839     4,161  .187327287   R-squared       =    0.1211
-------------+----------------------------------   Adj R-squared   =    0.1205
       Total |  886.904902     4,164  .212993492   Root MSE        =    .43281

------------------------------------------------------------------------------
       lwage | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
female_black |  -.6674001   .0428671   -15.57   0.000    -.7514426   -.5833576
female_non~k |  -.4341146   .0238361   -18.21   0.000     -.480846   -.3873832
  male_black |  -.2239593   .0317691    -7.05   0.000    -.2862436   -.1616749
       _cons |    6.74165   .0073159   921.51   0.000     6.727307    6.755993
------------------------------------------------------------------------------

 ( 1)  female_black - female_nonblack = 0

       F(  1,  4161) =   23.68
            Prob &gt; F =    0.0000</code></pre>
</div>
</div>
<p><strong>7.</strong> In each case, test equality across all four gender-ethnicity groups. Again, you should get the same result.</p>
<div id="27713587" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> lwage female_black female_nonblack male_black male_nonblack, <span class="kw">nocons</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="kw">test</span> female_black = female_nonblack = male_black = male_nonblack</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> lwage female <span class="bn">black</span> female_black</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="kw">test</span> female_black = <span class="bn">black</span> = female = 0</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> lwage female_black female_nonblack male_black  </span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="kw">test</span> female_black = female_nonblack = male_black = 0</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      Source |       SS           df       MS      Number of obs   =     4,165
-------------+----------------------------------   F(4, 4161)      &gt;  99999.00
       Model |  185756.485         4  46439.1213   Prob &gt; F        =    0.0000
    Residual |  779.468839     4,161  .187327287   R-squared       =    0.9958
-------------+----------------------------------   Adj R-squared   =    0.9958
       Total |  186535.954     4,165  44.7865436   Root MSE        =    .43281

------------------------------------------------------------------------------
       lwage | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
female_black |    6.07425   .0422382   143.81   0.000     5.991441     6.15706
female_non~k |   6.307536   .0226856   278.04   0.000      6.26306    6.352012
  male_black |   6.517691   .0309152   210.82   0.000     6.457081    6.578301
male_nonbl~k |    6.74165   .0073159   921.51   0.000     6.727307    6.755993
------------------------------------------------------------------------------

 ( 1)  female_black - female_nonblack = 0
 ( 2)  female_black - male_black = 0
 ( 3)  female_black - male_nonblack = 0

       F(  3,  4161) =  191.17
            Prob &gt; F =    0.0000

      Source |       SS           df       MS      Number of obs   =     4,165
-------------+----------------------------------   F(3, 4161)      =    191.17
       Model |  107.436063         3  35.8120209   Prob &gt; F        =    0.0000
    Residual |  779.468839     4,161  .187327287   R-squared       =    0.1211
-------------+----------------------------------   Adj R-squared   =    0.1205
       Total |  886.904902     4,164  .212993492   Root MSE        =    .43281

------------------------------------------------------------------------------
       lwage | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
      female |  -.4341146   .0238361   -18.21   0.000     -.480846   -.3873832
       black |  -.2239593   .0317691    -7.05   0.000    -.2862436   -.1616749
female_black |  -.0093263    .057515    -0.16   0.871    -.1220865    .1034339
       _cons |    6.74165   .0073159   921.51   0.000     6.727307    6.755993
------------------------------------------------------------------------------

 ( 1)  - black + female_black = 0
 ( 2)  - female + female_black = 0
 ( 3)  female_black = 0

       F(  3,  4161) =  191.17
            Prob &gt; F =    0.0000

      Source |       SS           df       MS      Number of obs   =     4,165
-------------+----------------------------------   F(3, 4161)      =    191.17
       Model |  107.436063         3  35.8120209   Prob &gt; F        =    0.0000
    Residual |  779.468839     4,161  .187327287   R-squared       =    0.1211
-------------+----------------------------------   Adj R-squared   =    0.1205
       Total |  886.904902     4,164  .212993492   Root MSE        =    .43281

------------------------------------------------------------------------------
       lwage | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
female_black |  -.6674001   .0428671   -15.57   0.000    -.7514426   -.5833576
female_non~k |  -.4341146   .0238361   -18.21   0.000     -.480846   -.3873832
  male_black |  -.2239593   .0317691    -7.05   0.000    -.2862436   -.1616749
       _cons |    6.74165   .0073159   921.51   0.000     6.727307    6.755993
------------------------------------------------------------------------------

 ( 1)  female_black - female_nonblack = 0
 ( 2)  female_black - male_black = 0
 ( 3)  female_black = 0

       F(  3,  4161) =  191.17
            Prob &gt; F =    0.0000</code></pre>
</div>
</div>
<p><strong>8.</strong> Try to replicate the F-statistic for one of the above models. Hint, the F-stat for these models is the same as that of the whole model.</p>
<div id="d515a0e6" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> lwage female <span class="bn">black</span> female_black</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="kw">ereturn</span> <span class="ot">list</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> fstat = (<span class="fu">e</span>(r2)*<span class="fu">e</span>(df_r))/((1-<span class="fu">e</span>(r2))*<span class="fu">e</span>(df_m))</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> <span class="ot">list</span> fstat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      Source |       SS           df       MS      Number of obs   =     4,165
-------------+----------------------------------   F(3, 4161)      =    191.17
       Model |  107.436063         3  35.8120209   Prob &gt; F        =    0.0000
    Residual |  779.468839     4,161  .187327287   R-squared       =    0.1211
-------------+----------------------------------   Adj R-squared   =    0.1205
       Total |  886.904902     4,164  .212993492   Root MSE        =    .43281

------------------------------------------------------------------------------
       lwage | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
      female |  -.4341146   .0238361   -18.21   0.000     -.480846   -.3873832
       black |  -.2239593   .0317691    -7.05   0.000    -.2862436   -.1616749
female_black |  -.0093263    .057515    -0.16   0.871    -.1220865    .1034339
       _cons |    6.74165   .0073159   921.51   0.000     6.727307    6.755993
------------------------------------------------------------------------------

scalars:
                  e(N) =  4165
               e(df_m) =  3
               e(df_r) =  4161
                  e(F) =  191.1735422330181
                 e(r2) =  .1211359442526956
               e(rmse) =  .4328132235793649
                e(mss) =  107.4360627542734
                e(rss) =  779.4688391479763
               e(r2_a) =  .1205023003768864
                 e(ll) =  -2419.902951629166
               e(ll_0) =  -2688.805870567022
               e(rank) =  4

macros:
            e(cmdline) : "regress lwage female black female_black"
              e(title) : "Linear regression"
          e(marginsok) : "XB default"
                e(vce) : "ols"
             e(depvar) : "lwage"
                e(cmd) : "regress"
         e(properties) : "b V"
            e(predict) : "regres_p"
              e(model) : "ols"
          e(estat_cmd) : "regress_estat"

matrices:
                  e(b) :  1 x 4
                  e(V) :  4 x 4
               e(beta) :  1 x 3

functions:
             e(sample)   
     fstat =  191.17354</code></pre>
</div>
</div>
<p>In the case where the F-test corresponds to the test of the entire model, you can write the F-statistic in terms of <span class="math inline">\(R^2\)</span>.</p>
<p><strong>9.</strong> Estimate the following model:</p>
<p><span class="math display">\[
    lwage = \beta_1 + \beta_2F + \beta_3B + \beta_4F\times B + \beta_5exp + \beta_6exp^2 + \beta_7educ + \varepsilon
\]</span></p>
<ul>
<li><p>Interpret the estimated coeffiecients <span class="math inline">\(\hat{\beta}_7\)</span>.</p></li>
<li><p>Interpret the effect of experience variable <code>exp</code>. Use the median level of experience to make your calculation.</p></li>
</ul>
<div id="7ab50dee" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="kw">sum</span> educ, <span class="fu">det</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> lwage i.female##i.<span class="bn">black</span> exper expsq educ</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> (<span class="fu">exp</span>(_b[educ])-1)*100</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                     years of education
-------------------------------------------------------------
      Percentiles      Smallest
 1%            6              4
 5%            8              4
10%            9              4       Obs               4,165
25%           12              4       Sum of wgt.       4,165

50%           12                      Mean           12.84538
                        Largest       Std. dev.      2.787995
75%           16             17
90%           17             17       Variance       7.772916
95%           17             17       Skewness      -.2581161
99%           17             17       Kurtosis        2.71273

      Source |       SS           df       MS      Number of obs   =     4,165
-------------+----------------------------------   F(6, 4158)      =    411.81
       Model |     330.586         6  55.0976667   Prob &gt; F        =    0.0000
    Residual |  556.318902     4,158   .13379483   R-squared       =    0.3727
-------------+----------------------------------   Adj R-squared   =    0.3718
       Total |  886.904902     4,164  .212993492   Root MSE        =    .36578

------------------------------------------------------------------------------
       lwage | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
    1.female |  -.4032047   .0203208   -19.84   0.000    -.4430444    -.363365
     1.black |  -.1551546   .0269249    -5.76   0.000    -.2079417   -.1023674
             |
female#black |
        1 1  |   -.002071   .0488405    -0.04   0.966    -.0978246    .0936826
             |
       exper |   .0427346   .0022404    19.07   0.000     .0383422     .047127
       expsq |  -.0006982   .0000494   -14.14   0.000    -.0007951   -.0006014
        educ |   .0731837   .0020983    34.88   0.000     .0690698    .0772975
       _cons |   5.303667   .0362462   146.32   0.000     5.232606    5.374729
------------------------------------------------------------------------------
7.5928119</code></pre>
</div>
</div>
<ul>
<li>A one unit increase in years of educ is associated with an increase of 7.59% in expected wages, holding other regressors fixed.</li>
</ul>
<div id="52c5dd5a" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="kw">sum</span> exper, <span class="fu">det</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">return</span> <span class="ot">list</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> (<span class="fu">exp</span>(_b[exper]+2*<span class="fu">r</span>(p50)*_b[expsq])-1)*100</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
             years of full-time work experience
-------------------------------------------------------------
      Percentiles      Smallest
 1%            3              1
 5%            5              1
10%            7              1       Obs               4,165
25%           11              1       Sum of wgt.       4,165

50%           18                      Mean           19.85378
                        Largest       Std. dev.      10.96637
75%           29             50
90%           36             50       Variance       120.2613
95%           39             50       Skewness       .4000014
99%           44             51       Kurtosis       2.072064

scalars:
                  r(N) =  4165
              r(sum_w) =  4165
               r(mean) =  19.85378151260504
                r(Var) =  120.2612759224727
                 r(sd) =  10.96637022548814
           r(skewness) =  .4000013893781186
           r(kurtosis) =  2.072064120792274
                r(sum) =  82691
                r(min) =  1
                r(max) =  51
                 r(p1) =  3
                 r(p5) =  5
                r(p10) =  7
                r(p25) =  11
                r(p50) =  18
                r(p75) =  29
                r(p90) =  36
                r(p95) =  39
                r(p99) =  44
1.7754427</code></pre>
</div>
</div>
<ul>
<li>A one unit incease in years of experience is associated with an increase of 1.78% in expected wages, holding other regressors fixed.</li>
</ul>
<p><strong>10.</strong> Theoretically, how would you test the following restrictions for the model below?</p>
<ol type="a">
<li><p><span class="math inline">\(\beta_2 = \beta_3\)</span></p></li>
<li><p><span class="math inline">\(\beta_4 + \beta_5 = 1\)</span></p></li>
<li><p><span class="math inline">\(\beta_2 = \beta_3\)</span> <strong>and</strong> <span class="math inline">\(\beta_4 + \beta_5 = 1\)</span></p></li>
</ol>
<p><span class="math display">\[
    Y = \beta_1 + \beta_2X_2 + \beta_3X_3 + \beta_4X_4 + \beta_5X_5 + \varepsilon
\]</span></p>
<ol type="a">
<li>Restrictions 1: <span class="math inline">\(H_0: \beta_2 = \beta_3\Rightarrow \beta_2-\beta_3 = 0\)</span>. This can be written as a simple T-test (or F-tests),</li>
</ol>
<p><span class="math display">\[
\text{T-stat}  = \frac{\hat{\beta}_2-\hat{\beta}_3}{\sqrt{\hat{Var}(\hat{\beta}_2-\hat{\beta}_3)}}
\]</span></p>
<p>where,</p>
<p><span class="math display">\[
Var(\hat{\beta}_2-\hat{\beta}_3) = Var(\hat{\beta}_2) + Var(\hat{\beta}_3)-2\cdot Cov(\hat{\beta}_2,\hat{\beta}_3)
\]</span></p>
<p>Alternatively, rewrite the model, adding and subtracting <span class="math inline">\(\beta_3X_2\)</span> (or <span class="math inline">\(\beta_2X_3\)</span>):</p>
<p><span class="math display">\[
    Y = \beta_1 + (\beta_2-\beta_3)X_2 + \beta_3(X_2+X_3) + \beta_4X_4 + \beta_5X_5 + \varepsilon
\]</span></p>
<p>Then test the hypothese that the coefficient on <span class="math inline">\(X_2\)</span> is <span class="math inline">\(=0\)</span>.</p>
<ol start="2" type="a">
<li>Restrictions 1: <span class="math inline">\(H_0: \beta_4 + \beta_5 = 1\)</span>. This can be written as a simple T-test,</li>
</ol>
<p><span class="math display">\[
\text{T-stat} = \frac{\hat{\beta}_4+\hat{\beta}_5-1}{\sqrt{\hat{Var}(\hat{\beta}_4+\hat{\beta}_5})}
\]</span></p>
<p>where,</p>
<p><span class="math display">\[
Var(\hat{\beta}_4+\hat{\beta}_5) = Var(\hat{\beta}_4) + Var(\hat{\beta}_5)+2\cdot Cov(\hat{\beta}_4,\hat{\beta}_5)
\]</span></p>
<p>Alternatively, rewrite the model, adding and subtracting <span class="math inline">\(\beta_5X_4-X_5\)</span> (or <span class="math inline">\(\beta_2X_3\)</span>):</p>
<p><span class="math display">\[
    Y-X_4 = \beta_1 + \beta_2X_2 + \beta_3X_3 + (\beta_4+\beta_5-1)X_4 + (\beta_5)(X_5-X_4) + \varepsilon
\]</span></p>
<p>Then test the hypothese that the coefficient on <span class="math inline">\(X_4\)</span> is <span class="math inline">\(=0\)</span>.</p>
<ol start="3" type="a">
<li>To test both of the linear restrictions simultaneously, we would use an F-test.</li>
</ol>
<p>Step 1: estimate the unrestricted model</p>
<p><span class="math display">\[
    Y = \beta_1 + \beta_2X_2 + \beta_3X_3 + \beta_4X_4 + \beta_5X_5 + \varepsilon
\]</span></p>
<p>Store the <span class="math inline">\(SSR_U\)</span></p>
<p>Step 2: estimate the restricted model</p>
<p><span class="math display">\[
    (Y-X_4) = \gamma_1 + \gamma_2(X_2+X_3) + \gamma_5(X_5-X_4) + \varepsilon
\]</span></p>
<p>Store the <span class="math inline">\(SSR_R\)</span>.</p>
<p>Step 3: Compute the F-statistic</p>
<p><span class="math display">\[
\text{F-stat} = \frac{(SSR_R-SSR_U)/(df_R-df_U)}{SSR_U/df_U}
\]</span></p>
</section>
<section id="postamble" class="level2">
<h2 class="anchored" data-anchor-id="postamble">Postamble</h2>
<div id="d7ff1756" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">log</span> <span class="kw">close</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>